base: ../../base/datasets/autsl.yaml

processing:
  enabled: true
  processor: video2crop
  detection: yolo
  sample_rate: 0.5
  max_workers: 4
  detection_config:
    model: yolo11m.pt
    device: cpu
    confidence_threshold: 0.5
    batch_size: 16
  video_config:
    codec: libx264
    padding: 0.0

post_processing:
  enabled: false

output:
  enabled: true

run_name: default

paths:
  root: dataset/autsl
  videos: dataset/autsl
  manifest: dataset/autsl/manifest.tsv
